# Form implementation generated from reading ui file 'category_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource_new_tr_dialog

class Ui_category_dialog(object):
    def setupUi(self, category_dialog):
        category_dialog.setObjectName("category_dialog")
        category_dialog.resize(505, 260)
        category_dialog.setMinimumSize(QtCore.QSize(505, 260))
        category_dialog.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.767363, y2:0.937, stop:0.590909 rgba(56, 166, 123, 255), stop:0.846591 rgba(0, 0, 0, 236));\n"
"font: Noto Sans;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(category_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.categories_frame = QtWidgets.QFrame(parent=category_dialog)
        self.categories_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.categories_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.categories_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.categories_frame.setObjectName("categories_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.categories_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.categories_frame)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 15pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.remove_categories_cmb_box = QtWidgets.QComboBox(parent=self.categories_frame)
        self.remove_categories_cmb_box.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QComboBox QListView {\n"
"font-size: 16px;\n"
"background-color: gray;\n"
"color: white;\n"
"}")
        self.remove_categories_cmb_box.setCurrentText("")
        self.remove_categories_cmb_box.setObjectName("remove_categories_cmb_box")
        self.verticalLayout.addWidget(self.remove_categories_cmb_box)
        self.add_categories_cmb_box = QtWidgets.QComboBox(parent=self.categories_frame)
        self.add_categories_cmb_box.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QComboBox QListView {\n"
"font-size: 16px;\n"
"background-color: gray;\n"
"color: white;\n"
"}")
        self.add_categories_cmb_box.setObjectName("add_categories_cmb_box")
        self.verticalLayout.addWidget(self.add_categories_cmb_box)
        self.save_btn = QtWidgets.QPushButton(parent=self.categories_frame)
        self.save_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"font-size: 13pt;\n"
"background-color: none;\n"
"border: 1px solid white;\n"
"border-radius: 7px;\n"
"height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 30)\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70)\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.save_btn.setIcon(icon)
        self.save_btn.setIconSize(QtCore.QSize(24, 24))
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.label = QtWidgets.QLabel(parent=self.categories_frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"font-size: 25pt;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.new_category_btn = QtWidgets.QPushButton(parent=self.categories_frame)
        self.new_category_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"font-size: 13pt;\n"
"background-color: none;\n"
"border: 1px solid white;\n"
"border-radius: 7px;\n"
"height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 30)\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70)\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/category_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.new_category_btn.setIcon(icon1)
        self.new_category_btn.setIconSize(QtCore.QSize(20, 20))
        self.new_category_btn.setObjectName("new_category_btn")
        self.verticalLayout.addWidget(self.new_category_btn)
        self.verticalLayout_2.addWidget(self.categories_frame)

        self.retranslateUi(category_dialog)
        self.remove_categories_cmb_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(category_dialog)

    def retranslateUi(self, category_dialog):
        _translate = QtCore.QCoreApplication.translate
        category_dialog.setWindowTitle(_translate("category_dialog", "Category"))
        self.label_2.setText(_translate("category_dialog", "Заменить категорию на главном экране"))
        self.save_btn.setText(_translate("category_dialog", "Сохранить изменения"))
        self.label.setText(_translate("category_dialog", "ИЛИ"))
        self.new_category_btn.setText(_translate("category_dialog", "Создать новую категорию"))
