# Form implementation generated from reading ui file 'make_graph_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graphs_dialog(object):
    def setupUi(self, graphs_dialog):
        graphs_dialog.setObjectName("graphs_dialog")
        graphs_dialog.resize(759, 511)
        graphs_dialog.setMinimumSize(QtCore.QSize(750, 500))
        graphs_dialog.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.767363, y2:0.937, stop:0.590909 rgba(56, 166, 123, 255), stop:0.846591 rgba(0, 0, 0, 236));\n"
"font: Noto Sans;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(graphs_dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=graphs_dialog)
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("color: white;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.start_date_edit = QtWidgets.QDateEdit(parent=self.frame_2)
        self.start_date_edit.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;")
        self.start_date_edit.setDate(QtCore.QDate(2024, 11, 10))
        self.start_date_edit.setObjectName("start_date_edit")
        self.horizontalLayout_6.addWidget(self.start_date_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.calendarWidget_start = QtWidgets.QCalendarWidget(parent=self.frame_2)
        self.calendarWidget_start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget_start.setObjectName("calendarWidget_start")
        self.verticalLayout.addWidget(self.calendarWidget_start)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 14pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.end_date_edit = QtWidgets.QDateEdit(parent=self.frame_2)
        self.end_date_edit.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;")
        self.end_date_edit.setDate(QtCore.QDate(2024, 11, 10))
        self.end_date_edit.setObjectName("end_date_edit")
        self.horizontalLayout_7.addWidget(self.end_date_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.calendarWidget_end = QtWidgets.QCalendarWidget(parent=self.frame_2)
        self.calendarWidget_end.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget_end.setObjectName("calendarWidget_end")
        self.verticalLayout_3.addWidget(self.calendarWidget_end)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.cb = QtWidgets.QComboBox(parent=self.frame_2)
        self.cb.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QComboBox QListView {\n"
"font-size: 16px;\n"
"background-color: gray;\n"
"color: white;\n"
"}")
        self.cb.setObjectName("cb")
        self.cb.addItem("")
        self.cb.addItem("")
        self.cb.addItem("")
        self.verticalLayout_2.addWidget(self.cb)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.income_rb = QtWidgets.QRadioButton(parent=self.frame_2)
        self.income_rb.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"padding-top: 10px;")
        self.income_rb.setObjectName("income_rb")
        self.horizontalLayout_8.addWidget(self.income_rb)
        self.outcome_rb = QtWidgets.QRadioButton(parent=self.frame_2)
        self.outcome_rb.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"padding-top: 10px;")
        self.outcome_rb.setObjectName("outcome_rb")
        self.horizontalLayout_8.addWidget(self.outcome_rb)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.make_plots_btn = QtWidgets.QPushButton(parent=self.frame_2)
        self.make_plots_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 3px solid rgb(255,255,255);\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"     border-radius:7px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,50);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        self.make_plots_btn.setObjectName("make_plots_btn")
        self.verticalLayout_6.addWidget(self.make_plots_btn)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(graphs_dialog)
        QtCore.QMetaObject.connectSlotsByName(graphs_dialog)

    def retranslateUi(self, graphs_dialog):
        _translate = QtCore.QCoreApplication.translate
        graphs_dialog.setWindowTitle(_translate("graphs_dialog", "MakeGraph"))
        self.label.setText(_translate("graphs_dialog", "Дата начала выборки:"))
        self.label_2.setText(_translate("graphs_dialog", "Дата конца выборки:"))
        self.cb.setItemText(0, _translate("graphs_dialog", "По дням"))
        self.cb.setItemText(1, _translate("graphs_dialog", "По месяцам"))
        self.cb.setItemText(2, _translate("graphs_dialog", "По годам"))
        self.income_rb.setText(_translate("graphs_dialog", "Доход"))
        self.outcome_rb.setText(_translate("graphs_dialog", "Расход"))
        self.make_plots_btn.setText(_translate("graphs_dialog", "Построить графики"))
