# Form implementation generated from reading ui file 'transaction_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource_new_tr_dialog

class Ui_tr_dialog(object):
    def setupUi(self, tr_dialog):
        tr_dialog.setObjectName("tr_dialog")
        tr_dialog.resize(351, 377)
        tr_dialog.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.767363, y2:0.937, stop:0.590909 rgba(56, 166, 123, 255), stop:0.846591 rgba(0, 0, 0, 236));\n"
"font: Noto Sans;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(tr_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tr_frame = QtWidgets.QFrame(parent=tr_dialog)
        self.tr_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.tr_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tr_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tr_frame.setObjectName("tr_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tr_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tr_lbl = QtWidgets.QLabel(parent=self.tr_frame)
        self.tr_lbl.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"padding-top: 10px;")
        self.tr_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tr_lbl.setObjectName("tr_lbl")
        self.verticalLayout.addWidget(self.tr_lbl)
        self.cb_choose_category = QtWidgets.QComboBox(parent=self.tr_frame)
        self.cb_choose_category.setStyleSheet("QComboBox {\n"
"font-size: 16pt;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QComboBox QListView {\n"
"font-size: 16px;\n"
"background-color: gray;\n"
"color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"color: green;\n"
"}")
        self.cb_choose_category.setEditable(False)
        self.cb_choose_category.setCurrentText("")
        self.cb_choose_category.setDuplicatesEnabled(False)
        self.cb_choose_category.setFrame(True)
        self.cb_choose_category.setObjectName("cb_choose_category")
        self.verticalLayout.addWidget(self.cb_choose_category)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.tr_frame)
        self.dateEdit.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;")
        self.dateEdit.setDate(QtCore.QDate(2024, 11, 10))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.le_description = QtWidgets.QLineEdit(parent=self.tr_frame)
        self.le_description.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;")
        self.le_description.setObjectName("le_description")
        self.verticalLayout.addWidget(self.le_description)
        self.le_balance = QtWidgets.QLineEdit(parent=self.tr_frame)
        self.le_balance.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;")
        self.le_balance.setObjectName("le_balance")
        self.verticalLayout.addWidget(self.le_balance)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_income = QtWidgets.QRadioButton(parent=self.tr_frame)
        self.rb_income.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rb_income.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"padding-top: 10px;")
        self.rb_income.setObjectName("rb_income")
        self.horizontalLayout.addWidget(self.rb_income)
        self.rb_outcome = QtWidgets.QRadioButton(parent=self.tr_frame)
        self.rb_outcome.setStyleSheet("color: white;\n"
"font-size: 18pt;\n"
"background-color: none;\n"
"border: none;\n"
"font-weight: bold;\n"
"padding-top: 10px;")
        self.rb_outcome.setObjectName("rb_outcome")
        self.horizontalLayout.addWidget(self.rb_outcome)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_new_transaction = QtWidgets.QPushButton(parent=self.tr_frame)
        self.btn_new_transaction.setStyleSheet("QPushButton {\n"
"color: white;\n"
"font-size: 13pt;\n"
"background-color: none;\n"
"border: 1px solid white;\n"
"border-top-left-radius: 7px;\n"
"height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 30)\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70)\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_new_transaction.setIcon(icon)
        self.btn_new_transaction.setIconSize(QtCore.QSize(25, 25))
        self.btn_new_transaction.setObjectName("btn_new_transaction")
        self.verticalLayout.addWidget(self.btn_new_transaction)
        self.verticalLayout_2.addWidget(self.tr_frame)

        self.retranslateUi(tr_dialog)
        self.cb_choose_category.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(tr_dialog)

    def retranslateUi(self, tr_dialog):
        _translate = QtCore.QCoreApplication.translate
        tr_dialog.setWindowTitle(_translate("tr_dialog", "Transaction"))
        self.tr_lbl.setText(_translate("tr_dialog", "Новая транзакция"))
        self.le_description.setPlaceholderText(_translate("tr_dialog", "Описание"))
        self.le_balance.setPlaceholderText(_translate("tr_dialog", "Сумма"))
        self.rb_income.setText(_translate("tr_dialog", "Доход"))
        self.rb_outcome.setText(_translate("tr_dialog", "Расход"))
        self.btn_new_transaction.setText(_translate("tr_dialog", "Сохранить транзакцию"))
